// frontend/vue/student-management/src/components/CreateStudent.vue
<template>
  <f-popup v-on:confirm-popup="confirmStudent" v-bind:sync-data-of-components="syncDataOfComponents.syncDataWithComponentPopup">
    <div slot="header">
      <h5>Create Student</h5>
    </div>
    <div slot="body">
      <b-form-group id="input-group-1" label="Name:" label-for="input-1">
        <b-form-input id="input-1" v-model="student.name" type="text" required placeholder="Enter name"></b-form-input>
      </b-form-group>
      <b-form-group id="input-group-2" label="Age:" label-for="input-2">
        <b-form-input id="input-2" v-model="student.age" type="text" required placeholder="Enter age"></b-form-input>
      </b-form-group>
    </div>
  </f-popup>
</template>

<script>
export default {
  name: "f-create-student",
  props: {
    syncDataOfComponents: {
      syncDataWithComponentPopup: {}
    },
    afterClosePopupCreateStudent: {
      type: Function,
      required: true
    },
  },
  data () {
    return {
      student: {
        id: 0,
        name: '',
        age: ''
      },
      emptyStudent: {
        id: 0,
        name: '',
        age: ''
      }
    }
  },
  watch: {
  },
  methods: {
    confirmStudent () {
      this.$store.dispatch('addStudent', this.student)
      //this.$store.state.students.push(this.student);
      this.student = Object.assign(this.student, this.emptyStudent)
    }
  }
}
</script>

<style scoped>

</style>

// frontend/react/student-management/src/components/CreateStudent.js
import React from 'react';
import { connect } from 'react-redux'
import { Form } from 'react-bootstrap'
import Popup from './Popup'
import {createStudents} from "../store/Actions";

class CreateStudent extends React.Component {

    constructor(props) {
        super(props)
        this.state = {
            student: {
                id: 0,
                name: '',
                age: ''
            }
        }
    }

    render() {
        console.log('render CreateStudent')
        return (
            <Popup syncDataOfComponents = {this.props.syncDataOfComponents.syncDataWithComponentPopup} handleConfirm = {this.confirmStudent} headerProp = "Create Student">
                <Form.Group controlId="formBasicEmail">
                    <Form.Label>Name:</Form.Label>
                    <Form.Control type="text" placeholder="Enter name" onChange={(event) => {this.state.student.name = event.target.value}}/>
                </Form.Group>
                <Form.Group controlId="formBasicEmail">
                    <Form.Label>Age:</Form.Label>
                    <Form.Control type="number" placeholder="Enter age" onChange={(event) => {this.state.student.age = event.target.value}}/>
                </Form.Group>
            </Popup>
        )
    }

    confirmStudent = () => {
        console.log('CreateStudent confirmStudent')
        console.log(this.state.student)
        const {createStudents} = this.props;
        createStudents(this.state.student)
    }

}

const mapStateToProps = (state) => {
    return {
        students: state.students
    }
}

const mapDispatchToProps = (dispatch) => {
    return {
        createStudents: (student) => dispatch(createStudents(student))
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(CreateStudent)
