// frontend/vue/student-management/src/components/DeleteStudent.vue
<template>
  <f-popup v-on:confirm-popup="confirmStudent" v-on:open-popup="afterOpenPopup" v-bind:sync-data-of-components="syncDataOfComponents.syncDataWithComponentPopup">
    <div slot="header" >
      <h5>Delete student {{selectedStudent.id}}</h5>
    </div>
    <div slot="body">
      <h2 style="text-align: center">Are you sure?</h2>
    </div>
  </f-popup>
</template>

<script>
export default {
  name: "f-delete-student",
  props: {
    syncDataOfComponents: {
      syncDataWithComponentPopup: {}
    },
    selectedStudent: {
      type: Object,
      required: true
    }
  },
  data () {
    return {
      student: {
        id: 0,
        name: '',
        age: ''
      }
    }
  },
  mounted() {
  },
  watch: {
  },
  methods: {
    afterOpenPopup () {
      this.student.id = this.selectedStudent.id
    },
    confirmStudent () {
      this.$store.dispatch('deleteStudent', this.selectedStudent.id)
    }
  }
}
</script>

<style scoped>

</style>

// frontend/react/student-management/src/components/DeleteStudent.js
import React from 'react'
import { connect } from 'react-redux'
import Popup from './Popup'
import {deleteStudent} from "../store/Actions"

class DeleteStudent extends React.Component {

    constructor(props) {
        console.log('construct DeleteStudent')
        super(props)
        this.state = {
            student: {
                id: 0,
                name: '',
                age: ''
            }
        }
    }

    render() {
        console.log('render DeleteStudent')
        return (
            <Popup syncDataOfComponents = {this.props.syncDataOfComponents.syncDataWithComponentPopup} handleConfirm = {this.confirmStudent} headerProp = {"Delete Student " + this.props.selectedStudent.id}>
                <h2 style= {{ textAlign: "center" }}>Are you sure?</h2>
            </Popup>
        )
    }

    componentWillUpdate(nextProps, nextState) {
        console.log('DeleteStudent componentWillUpdate')
        if (nextProps.selectedStudent != this.props.selectedStudent) {
            this.state.student = nextProps.selectedStudent
        }
    }

    confirmStudent = () => {
        console.log('DeleteStudent confirmStudent')
        console.log(this.state.student)
        const {deleteStudent} = this.props;
        deleteStudent(this.state.student)
    }

}

const mapStateToProps = (state) => {
    return {
        students: state.students
    }
}

const mapDispatchToProps = (dispatch) => {
    return {
        deleteStudent: (student) => dispatch(deleteStudent(student))
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(DeleteStudent)
