// frontend/vue/student-management/src/components/EditStudent.vue
<template>
  <f-popup v-on:confirm-popup="confirmStudent" v-on:open-popup="afterOpenPopup" v-bind:sync-data-of-components="syncDataOfComponents.syncDataWithComponentPopup">
    <div slot="header">
      <h5>Edit student {{student.id}}</h5>
    </div>
    <div slot="body">
      <b-form-group id="edit-group-1" label="Name:" label-for="edit-1">
        <b-form-input id="edit-1" v-model="student.name" type="text" required placeholder="Enter name"></b-form-input>
      </b-form-group>
      <b-form-group id="edit-group-2" label="Age:" label-for="edit-2">
        <b-form-input id="edit-2" v-model="student.age" type="text" required placeholder="Enter age"></b-form-input>
      </b-form-group>
    </div>
  </f-popup>
</template>

<script>
export default {
  name: "f-edit-student",
  props: {
    syncDataOfComponents: {
      syncDataWithComponentPopup: {}
    },
    selectedStudent: {
      type: Object,
      required: true
    },
    afterClosePopupEditStudent: {
      type: Function,
      required: true
    }
  },
  data () {
    return {
      student: {
        id: 0,
        name: '',
        age: ''
      }
    }
  },
  mounted() {
  },
  watch: {
  },
  methods: {
    afterOpenPopup () {
      this.student = Object.assign(this.student, this.selectedStudent)
    },
    confirmStudent () {
      this.$store.dispatch('editStudent', this.student)
    }
  }
}
</script>

<style scoped>

</style>

// frontend/react/student-management/src/components/EditStudent.js
import React from 'react'
import { connect } from 'react-redux'
import { Form } from 'react-bootstrap'
import Popup from './Popup'
import {editStudent} from "../store/Actions"

class EditStudent extends React.Component {

    constructor(props) {
        console.log('construct EditStudent')
        super(props)
        this.state = {
            student: {
                id: 0,
                name: '',
                age: ''
            }
        }
    }

    render() {
        console.log('render EditStudent')
        return (
            <Popup syncDataOfComponents = {this.props.syncDataOfComponents.syncDataWithComponentPopup} handleConfirm = {this.confirmStudent} headerProp = "Edit Student">
                <Form.Group controlId="formBasicEmail">
                    <Form.Label>Name:</Form.Label>
                    <Form.Control type="text" placeholder="Enter name" value={this.state.student.name} onChange={(event) => this.changeDisplayedData(event, 'name')}/>
                </Form.Group>
                <Form.Group controlId="formBasicEmail">
                    <Form.Label>Age:</Form.Label>
                    <Form.Control type="number" placeholder="Enter age" value={this.state.student.age} onChange={(event) => this.changeDisplayedData(event, 'age')}/>
                </Form.Group>
            </Popup>
        )
    }

    componentWillUpdate(nextProps, nextState) {
        console.log('EditStudent componentWillUpdate')
        if (nextProps.selectedStudent != this.props.selectedStudent) {
            this.state.student = nextProps.selectedStudent
        }
    }

    changeDisplayedData(event, type) {
        const newStudent = {...this.state.student};
        newStudent[type] = event.target.value;
        this.setState({student: newStudent});
    }

    confirmStudent = () => {
        console.log('EditStudent confirmStudent')
        console.log(this.state.student)
        const {editStudent} = this.props;
        editStudent(this.state.student)
    }

}

const mapStateToProps = (state) => {
    return {
        students: state.students
    }
}

const mapDispatchToProps = (dispatch) => {
    return {
        editStudent: (student) => dispatch(editStudent(student))
    }
}

export default connect(mapStateToProps, mapDispatchToProps)(EditStudent)
