// frontend/vue/student-management/src/components/Popup.vue
<template>
  <div>
    <b-modal ref="my-modal" v-on:hide="afterHidePopup">
      <template v-slot:modal-header="{}">
        <slot name="header">
        </slot>
      </template>

      <template v-slot:default="{}">
        <slot name="body">
        </slot>
      </template>

      <template v-slot:modal-footer="{}">
        <slot name="footer">
          <b-button size="sm" variant="success" v-on:click="confirm">
            OK
          </b-button>
          <b-button size="sm" variant="danger" v-on:click="closePopup">
            Cancel
          </b-button>
        </slot>
      </template>
    </b-modal>
  </div>
</template>

<script>
export default {
  name: 'f-popup',
  props: {
    syncDataOfComponents: {
      requestRerender: 0,
      showPopup: false
    }
  },
  watch: {
    'syncDataOfComponents.requestRerender': function (val) {
      console.log(val)
      if (this.syncDataOfComponents.showPopup) {
        this.$refs['my-modal'].show()
        this.$emit('open-popup')
      } else {
        this.$refs['my-modal'].hide()
      }
    }
  },
  methods: {
    confirm () {
      this.$emit('confirm-popup')
      this.closePopup()
    },
    closePopup () {
      this.$refs['my-modal'].hide()
    },
    afterHidePopup() {
      // this.syncDataOfComponents.showPopup = false
    }
  }
}
</script>

<style scoped>

</style>

// frontend/react/student-management/src/components/Popup.js
import React from "react"
import { Button, Modal } from 'react-bootstrap'

class Popup extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            showPopup: false
        };
    }

    render() {
        console.log('render popup')

        return (
            <Modal show={this.state.showPopup} onHide={this.handleClose}>
                <Modal.Header closeButton>
                    <Modal.Title>{this.props.headerProp}</Modal.Title>
                </Modal.Header>
                <Modal.Body>{this.props.children}</Modal.Body>
                <Modal.Footer>
                    <Button variant="primary" onClick={this.handleConfirm}>
                        OK
                    </Button>
                    <Button variant="secondary" onClick={this.handleClose}>
                        Cancel
                    </Button>
                </Modal.Footer>
            </Modal>
        )
    }

    componentWillUpdate(nextProps, nextState) {
        console.log('componentWillUpdate')
        if (nextProps.syncDataOfComponents.requestRerender != this.props.syncDataOfComponents.requestRerender) {
            this.state.showPopup = nextProps.syncDataOfComponents.showPopup
        }
    }

    handleClose = () => {
        this.setState({showPopup: false})
    }

    handleConfirm = () => {
        this.props.handleConfirm()
        this.handleClose()
    }

}

export default Popup
