// frontend/vue/student-management/src/components/Student.vue
<template>
  <div>
    <div>
      <b-button v-on:click="popupAddStudent" style="margin-left: 10px">Add Student</b-button>
      <b-button v-on:click="back" style="float:right; margin-right:10px">Back</b-button>
    </div>
    <div style="text-align: center; margin-top: 10px">
      <b-table :items="this.$store.state.students" :fields="fields" striped responsive="sm">
        <template v-slot:cell(action)="row">
          <b-button size="sm" class="mr-2" v-on:click="popupEditStudent(row.item)">
            Edit
          </b-button>
          <b-button size="sm" class="mr-2" v-on:click="popupDeleteStudent(row.item)">
            Delete
          </b-button>
        </template>
      </b-table>
      <f-create-student v-bind:sync-data-of-components="syncDataWithComponentCreateStudent" v-bind:after-close-popup-create-student="afterClosePopupCreateStudent"></f-create-student>
      <f-edit-student v-bind:sync-data-of-components="syncDataWithComponentEditStudent" v-bind:selectedStudent="selectedStudent" v-bind:after-close-popup-edit-student="afterClosePopupEditStudent"></f-edit-student>
      <f-delete-student v-bind:sync-data-of-components="syncDataWithComponentDeleteStudent" v-bind:selectedStudent="selectedStudent"></f-delete-student>
    </div>
  </div>
</template>

<script>
export default {
  name: 'f-student',
  data () {
    return {
      syncDataWithComponentCreateStudent: {
        syncDataWithComponentPopup: {
          requestRerender: 0,
          showPopup: false
        }
      },
      syncDataWithComponentEditStudent: {
        syncDataWithComponentPopup: {
          requestRerender: 0,
          showPopup: false
        }
      },
      syncDataWithComponentDeleteStudent: {
        syncDataWithComponentPopup: {
          requestRerender: 0,
          showPopup: false
        }
      },
      fields: ['id', 'name', 'age', 'action'],
      selectedStudent: {
        id: 0,
        name: '',
        age: ''
      }
    }
  },
  created () {
    this.$store.dispatch('getAllStudents', this.student)
  },
  mounted () {
  },
  methods: {
    popupAddStudent () {
      this.syncDataWithComponentCreateStudent.syncDataWithComponentPopup.showPopup = true
      this.syncDataWithComponentCreateStudent.syncDataWithComponentPopup.requestRerender++
    },
    afterClosePopupCreateStudent () {
    },
    popupEditStudent (student) {
      this.syncDataWithComponentEditStudent.syncDataWithComponentPopup.showPopup = true
      this.syncDataWithComponentEditStudent.syncDataWithComponentPopup.requestRerender++
      this.selectedStudent = student
    },
    popupDeleteStudent (student) {
      this.syncDataWithComponentDeleteStudent.syncDataWithComponentPopup.showPopup = true
      this.syncDataWithComponentDeleteStudent.syncDataWithComponentPopup.requestRerender++
      this.selectedStudent = student
    },
    afterClosePopupEditStudent () {
    },
    back () {
      this.$router.push('/')
    }
  }
}
</script>

<style scoped>

</style>

// frontend/react/student-management/src/components/Student.js
import React from 'react'
import Table from 'react-bootstrap/Table';
import Button from 'react-bootstrap/Button'
import { connect } from 'react-redux'
import { getStudents } from '../store/Actions'
import CreateStudent from './CreateStudent'
import EditStudent from './EditStudent'
import DeleteStudent from './DeleteStudent'
import 'bootstrap/dist/css/bootstrap.min.css'
import '../css/student.css'

class Student extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            syncDataWithComponentCreateStudent: {
                syncDataWithComponentPopup: {
                    requestRerender: 0,
                    showPopup: false
                }
            },
            syncDataWithComponentEditStudent: {
                syncDataWithComponentPopup: {
                    requestRerender: 0,
                    showPopup: false
                }
            },
            syncDataWithComponentDeleteStudent: {
                syncDataWithComponentPopup: {
                    requestRerender: 0,
                    showPopup: false
                }
            },
            selectedStudent: {
                id: 0,
                name: '',
                age: ''
            }
        }
        this.loadData()
        // this.popupAddStudent = this.popupAddStudent.bind(this)
    }

    render() {
        let data = this.createTable();
        return (
            <div>
                <div>
                    <Button onClick={this.popupAddStudent} variant="secondary" style={{ marginLeft: "10px" }}>Add Student</Button>
                    <Button onClick={this.back} variant="secondary" style={{ float: "right", marginRight: "10px" }}>Back</Button>
                </div>
                <div style={{textAlign: "center", marginTop: "10px"}}>
                    <Table striped bordered hover style={{width: "100%"}}>
                        <thead>
                            <tr>
                                <th>id</th>
                                <th>name</th>
                                <th>age</th>
                                <th>action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {data}
                        </tbody>
                    </Table>
                    <CreateStudent syncDataOfComponents = {this.state.syncDataWithComponentCreateStudent}></CreateStudent>
                    <EditStudent syncDataOfComponents = {this.state.syncDataWithComponentEditStudent} selectedStudent = {this.state.selectedStudent}></EditStudent>
                    <DeleteStudent syncDataOfComponents = {this.state.syncDataWithComponentDeleteStudent} selectedStudent = {this.state.selectedStudent}></DeleteStudent>
                </div>
            </div>
        )
    }

    createTable() {
        console.log('createTable')
        const {students} = this.props;
        console.log(students)
        let table = []
        if (!students) {
            console.log('Students not found');
            return table
        }
        for (let i=0; i<students.length; i++) {
            let student = students[i]
            table.push (
                <tr>
                    <td>{student.id}</td>
                    <td>{student.name}</td>
                    <td>{student.age}</td>
                    <td>
                        <Button onClick={() => {this.popupEditStudent(student)}} variant="secondary">Edit</Button>
                        <Button onClick={() => {this.popupDeleteStudent(student)}} variant="secondary" style={{ marginLeft: "10px" }}>Delete</Button>
                    </td>
                </tr>
            )
        }
        return table;
    }

    componentDidMount() {
    }

    loadData() {
        console.log('loadData')
        const {getStudents} = this.props;
        getStudents()
    }

    popupAddStudent = () => {
        console.log('popupCreateStudent')
        let requestRerender = this.state.syncDataWithComponentCreateStudent.syncDataWithComponentPopup.requestRerender + 1
        this.setState({
            syncDataWithComponentCreateStudent: {
                syncDataWithComponentPopup: {
                    showPopup: true,
                    requestRerender: requestRerender

                }
            }
        })
    }

    popupEditStudent(student) {
        console.log('popupEditStudent')
        this.setState({
            selectedStudent: student,
            syncDataWithComponentEditStudent: {
                syncDataWithComponentPopup: {
                    showPopup: true,
                    requestRerender: this.state.syncDataWithComponentEditStudent.syncDataWithComponentPopup.requestRerender + 1

                }
            }
        })
    }

    popupDeleteStudent(student) {
        console.log('popupDeleteStudent')
        this.setState({
            selectedStudent: student,
            syncDataWithComponentDeleteStudent: {
                syncDataWithComponentPopup: {
                    showPopup: true,
                    requestRerender: this.state.syncDataWithComponentDeleteStudent.syncDataWithComponentPopup.requestRerender + 1

                }
            }
        })
    }

    back = () => {
        this.props.history.push('/')
    }
}

const mapStateToProps = (state) => {
    return {
        students: state.students
    };
};

const mapDispatchToProps = (dispatch) => {
    return {
        getStudents: () => dispatch(getStudents())
    };
};

export default connect(mapStateToProps, mapDispatchToProps)(Student);
