// frontend/react/student-management/src/components/FunctionList.js
import React from 'react';
import Button from 'react-bootstrap/Button';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../css/student.css';

class FunctionList extends React.Component {
    render() {
        return (
            <div>
                <div class="student-mngm-btn">
                    <Button block variant="primary" onClick={this.accessInnerPage}>Student</Button>
                </div>
                <div class="student-mngm-btn">
                    <Button block variant="primary" onClick={this.accessInnerPage}>Class</Button>
                </div>
            </div>
        );
    }

    accessInnerPage = () => {
        this.props.history.push('/student')
    }
}

export default FunctionList;

// frontend/vue/student-management/src/components/FunctionList.vue
<template>
  <div>
    <div class="student-mngm-btn">
      <b-button block variant="primary" v-on:click = "accessInnerPage">Student</b-button>
    </div>
    <div class="student-mngm-btn">
      <b-button block variant="primary" v-on:click = "accessInnerPage">Class</b-button>
    </div>
  </div>
</template>

<script>
export default {
  name: "f-function-list",
  methods: {
    accessInnerPage () {
      this.$router.push('student')
    }
  }
}
</script>

<style scoped>
  .student-mngm-btn {
    margin-bottom: 10px;
  }
</style>
